#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path


def normalize_phrase(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"\([^)]*\)", " ", s)
    s = s.replace("_", " ")
    s = s.replace("-", " ")
    s = re.sub(r"[^a-z0-9\s]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def split_synonyms(english_field: str) -> list[str]:
    raw = (english_field or "").strip()
    if not raw:
        return []
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    out: list[str] = []
    for p in parts:
        norm = normalize_phrase(p)
        if norm:
            out.append(norm)
    # unique, stable order
    seen: set[str] = set()
    uniq: list[str] = []
    for s in out:
        if s in seen:
            continue
        seen.add(s)
        uniq.append(s)
    return uniq


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a small JS data file for the toddler noun translator."
    )
    parser.add_argument(
        "--in-csv",
        type=Path,
        default=Path("Docs/toddler_nouns_yellow.csv"),
        help="Input CSV (default: Docs/toddler_nouns_yellow.csv).",
    )
    parser.add_argument(
        "--out-js",
        type=Path,
        default=Path("web/toddlerData.js"),
        help="Output JS file (default: web/toddlerData.js).",
    )
    parser.add_argument(
        "--image-base",
        default="bliss_h188_documentation_id_png",
        help="Relative image folder (default: bliss_h188_documentation_id_png).",
    )
    parser.add_argument(
        "--format",
        choices=["window", "esm"],
        default="window",
        help="Output format: window sets window.__TODDLER_DATA__; esm exports toddlerData (default: window).",
    )
    args = parser.parse_args()

    rows = []
    with args.in_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            symbol_id = (row.get("BCI-AV#") or "").strip()
            if not symbol_id.isdigit():
                continue
            synonyms = split_synonyms(row.get("English") or "")
            primary = synonyms[0] if synonyms else ""
            rows.append(
                {
                    "id": int(symbol_id),
                    "primary": primary,
                    "synonyms": synonyms,
                    "pos": (row.get("POS") or "").strip(),
                    "derivation": (row.get("Derivation - explanation") or "").strip(),
                    "img": f"{args.image_base}/{symbol_id}.png",
                }
            )

    rows.sort(key=lambda r: r["id"])

    payload = {
        "version": 1,
        "source": str(args.in_csv),
        "symbols": rows,
    }
    if args.format == "esm":
        js = (
            "// Auto-generated by scripts/build_toddler_translator_data.py\n"
            f"export const toddlerData = {json.dumps(payload, ensure_ascii=False)};\n"
        )
    else:
        js = (
            "// Auto-generated by scripts/build_toddler_translator_data.py\n"
            f"window.__TODDLER_DATA__ = {json.dumps(payload, ensure_ascii=False)};\n"
        )

    args.out_js.parent.mkdir(parents=True, exist_ok=True)
    args.out_js.write_text(js, encoding="utf-8")
    print(f"Wrote {len(rows)} symbols to {args.out_js}")


if __name__ == "__main__":
    main()
